[package]
name = "cairn"
description = "Cairn launcher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[lib]
name = "cairn_launcher"
path = "src/lib.rs"

[[bin]]
name = "cairn"
path = "src/main.rs"

[dependencies]
windows.workspace = true
optimizer_core.workspace = true

[build-dependencies]
embed-manifest = "1.4"
